services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: enterprise
      MYSQL_USER: Vanderson
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - enterprise_network

  app:
    image: openjdk:21
    container_name: enterprise-system-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/enterprise
      SPRING_DATASOURCE_USERNAME: Vanderson
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    command: ["sh", "-c", "dockerize -wait tcp://db:3306 -timeout 60s java -jar /app/enterprise-system-api.jar"]
    ports:
      - "8081:8080"
    networks:
      - enterprise_network

networks:
  enterprise_network:
    driver: bridge
